### PR TITLE
Update _config.butterfly.yml

### PR DESCRIPTION
**Pull request by Longray-addicted-ZUTOMAYO**
Wrong QQ, have fixed.

### CODE REVIEW

**Comment by Longray-addicted-ZUTOMAYO** [comment]
Is this email automatically generated by Git？



---Original---
From: ***@***.***&gt;
Date: Wed, Sep 18, 2024 22:46 PM
To: ***@***.***&gt;;
Cc: " ***@***.******@***.***&gt;;
Subject: Re: [Octopus058/Octopus058.github.io] Update _config.butterfly.yml(PR #2)




 
Merged #2 into main.

**Comment by Octopus058** [comment]
@Longray-addicted-ZUTOMAYO yes

**Comment by Longray-addicted-ZUTOMAYO** [comment]
creamy dragon



---Original---
From: ***@***.***&gt;
Date: Fri, Sep 20, 2024 00:02 AM
To: ***@***.***&gt;;
Cc: " ***@***.******@***.***&gt;;
Subject: Re: [Octopus058/Octopus058.github.io] Update _config.butterfly.yml(PR #2)




 
@Longray-addicted-ZUTOMAYO yes

**Comment by Octopus058** [comment]
❤️

**Comment by Octopus058** [comment]
> creamy dragon
> […](#)
> ---Original--- From: ***@***.***&gt; Date: Fri, Sep 20, 2024 00:02 AM To: ***@***.***&gt;; Cc: " ***@***.******@***.***&gt;; Subject: Re: [Octopus058/Octopus058.github.io] Update _config.butterfly.yml(PR #2) @Longray-addicted-ZUTOMAYO yes — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned.Message ID: ***@***.***&gt;

❤️

**Comment by Octopus058** [comment]
> thirsty to death
> […](#)
> ---Original--- From: ***@***.***&gt; Date: Fri, Sep 20, 2024 07:57 AM To: ***@***.***&gt;; Cc: " ***@***.******@***.***&gt;; Subject: Re: [Octopus058/Octopus058.github.io] Update _config.butterfly.yml(PR #2) creamy dragon … ---Original--- From: @.&gt; Date: Fri, Sep 20, 2024 00:02 AM To: @.&gt;; Cc: " @.@.&gt;; Subject: Re: [Octopus058/Octopus058.github.io] Update _config.butterfly.yml(PR #2) @Longray-addicted-ZUTOMAYO yes — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned.Message ID: @.***&gt; ❤️ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned.Message ID: ***@***.***&gt;

❤️

**Comment by Longray-addicted-ZUTOMAYO** [comment]
---Original---
From: ***@***.***&gt;
Date: Fri, Sep 20, 2024 08:16 AM
To: ***@***.***&gt;;
Cc: " ***@***.******@***.***&gt;;
Subject: Re: [Octopus058/Octopus058.github.io] Update _config.butterfly.yml(PR #2)




  
thirsty to death
 …
 ---Original--- From: @.&gt; Date: Fri, Sep 20, 2024 07:57 AM To: @.&gt;; Cc: " @.@.&gt;; Subject: Re: [Octopus058/Octopus058.github.io] Update _config.butterfly.yml(PR #2) creamy dragon … ---Original--- From: @.&gt; Date: Fri, Sep 20, 2024 00:02 AM To: @.&gt;; Cc: " @.@.&gt;; Subject: Re: [Octopus058/Octopus058.github.io] Update _config.butterfly.yml(PR #2) @Longray-addicted-ZUTOMAYO yes — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned.Message ID: @.&gt; ❤️ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned.Message ID: @.&gt;
  
❤️

**Pull request merged**
